services:
  inventory-postgres:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-postgres
    volumes:
      - synasishouse_inventory_pg_data:/var/lib/postgresql/data
  inventory-backend:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-backend
    depends_on:
      inventory-postgres:
        condition: service_healthy
  order-postgres:
    extends:
      file: order-service/compose.yaml
      service: order-postgres
    volumes:
      - synasishouse_order_pg_data:/var/lib/postgresql/data
  order-backend:
    extends:
      file: order-service/compose.yaml
      service: order-backend
    depends_on:
      order-postgres:
        condition: service_healthy
      inventory-backend:
        condition: service_healthy

volumes:
  synasishouse_inventory_pg_data:
    name: synasishouse-inventory-pg-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: inventory/storage/pg_data
  synasishouse_order_pg_data:
    name: synasishouse-order-pg-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: order/storage/pg_data
