services:
  inventory-postgres:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-postgres
    volumes:
      - synansishouse_inventory_pgdata:/var/lib/postgresql/data
  inventory-backend:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-backend
    depends_on:
      inventory-postgres:
        condition: service_healthy
  order-backend:
    extends:
      file: order-service/compose.yaml
      service: order-backend
    depends_on:
      inventory-backend:
        condition: service_healthy

volumes:
  synansishouse_inventory_pgdata:
    name: synansishouse-inventory-pgdata
    driver: local
    driver_opts:
      o: bind
      type: none
      device: storage/inventory/pgdata
