services:
  inventory-postgres:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-postgres
    volumes:
      - synansishouse_inventory_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  inventory-backend:
    extends:
      file: inventory-service/compose.yaml
      service: inventory-backend
    depends_on:
      inventory-postgres:
        condition: service_healthy

volumes:
  synansishouse_inventory_pgdata:
    name: synansishouse-inventory-pgdata
    driver: local
    driver_opts:
      o: bind
      type: none
      device: inventory-service/tmp/pgdata
