// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        uuid.UUID          `json:"id"`
	OrderNo   string             `json:"order_no"`
	UserID    uuid.UUID          `json:"user_id"`
	Status    string             `json:"status"`
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type OrderDetail struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductCode string    `json:"product_code"`
	Amount      int32     `json:"amount"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
}
