// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_no,
    user_id,
    status
) VALUES (
    $1, $2, $3
) RETURNING id, order_no, user_id, status, expired_at, updated_at, created_at
`

type CreateOrderParams struct {
	OrderNo string    `json:"order_no"`
	UserID  uuid.UUID `json:"user_id"`
	Status  string    `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.OrderNo, arg.UserID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.ExpiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrder = `-- name: GetUserOrder :one
SELECT id, order_no, user_id, status, expired_at, updated_at, created_at FROM orders
WHERE
    order_no = $1
    AND user_id = $2
LIMIT 1
`

type GetUserOrderParams struct {
	OrderNo string    `json:"order_no"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserOrder(ctx context.Context, arg GetUserOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getUserOrder, arg.OrderNo, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.ExpiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
    status = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, order_no, user_id, status, expired_at, updated_at, created_at
`

type UpdateOrderStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.ExpiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
