// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: rpc_get_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_rpc_get_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rpc_get_product_proto protoreflect.FileDescriptor

const file_rpc_get_product_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_get_product.proto\x12\x02pb\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB%Z#github.com/ymanshur/synasishouse/pbb\x06proto3"

var (
	file_rpc_get_product_proto_rawDescOnce sync.Once
	file_rpc_get_product_proto_rawDescData []byte
)

func file_rpc_get_product_proto_rawDescGZIP() []byte {
	file_rpc_get_product_proto_rawDescOnce.Do(func() {
		file_rpc_get_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_product_proto_rawDesc), len(file_rpc_get_product_proto_rawDesc)))
	})
	return file_rpc_get_product_proto_rawDescData
}

var file_rpc_get_product_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_get_product_proto_goTypes = []any{
	(*GetProductRequest)(nil), // 0: pb.GetProductRequest
}
var file_rpc_get_product_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_get_product_proto_init() }
func file_rpc_get_product_proto_init() {
	if File_rpc_get_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_product_proto_rawDesc), len(file_rpc_get_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_product_proto_goTypes,
		DependencyIndexes: file_rpc_get_product_proto_depIdxs,
		MessageInfos:      file_rpc_get_product_proto_msgTypes,
	}.Build()
	File_rpc_get_product_proto = out.File
	file_rpc_get_product_proto_goTypes = nil
	file_rpc_get_product_proto_depIdxs = nil
}
