// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: rpc_get_stock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_rpc_get_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetStockRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type StockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_rpc_get_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_rpc_get_stock_proto protoreflect.FileDescriptor

const file_rpc_get_stock_proto_rawDesc = "" +
	"\n" +
	"\x13rpc_get_stock.proto\x12\x02pb\"=\n" +
	"\x0fGetStockRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"2\n" +
	"\rStockResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailableB%Z#github.com/ymanshur/synasishouse/pbb\x06proto3"

var (
	file_rpc_get_stock_proto_rawDescOnce sync.Once
	file_rpc_get_stock_proto_rawDescData []byte
)

func file_rpc_get_stock_proto_rawDescGZIP() []byte {
	file_rpc_get_stock_proto_rawDescOnce.Do(func() {
		file_rpc_get_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_stock_proto_rawDesc), len(file_rpc_get_stock_proto_rawDesc)))
	})
	return file_rpc_get_stock_proto_rawDescData
}

var file_rpc_get_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_stock_proto_goTypes = []any{
	(*GetStockRequest)(nil), // 0: pb.GetStockRequest
	(*StockResponse)(nil),   // 1: pb.StockResponse
}
var file_rpc_get_stock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_get_stock_proto_init() }
func file_rpc_get_stock_proto_init() {
	if File_rpc_get_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_stock_proto_rawDesc), len(file_rpc_get_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_stock_proto_goTypes,
		DependencyIndexes: file_rpc_get_stock_proto_depIdxs,
		MessageInfos:      file_rpc_get_stock_proto_msgTypes,
	}.Build()
	File_rpc_get_stock_proto = out.File
	file_rpc_get_stock_proto_goTypes = nil
	file_rpc_get_stock_proto_depIdxs = nil
}
