// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: rpc_create_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_rpc_create_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateProductRequest) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_rpc_create_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_rpc_create_product_proto protoreflect.FileDescriptor

const file_rpc_create_product_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_create_product.proto\x12\x02pb\x1a\rproduct.proto\"@\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"8\n" +
	"\x0fProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.pb.ProductR\aproductB%Z#github.com/ymanshur/synasishouse/pbb\x06proto3"

var (
	file_rpc_create_product_proto_rawDescOnce sync.Once
	file_rpc_create_product_proto_rawDescData []byte
)

func file_rpc_create_product_proto_rawDescGZIP() []byte {
	file_rpc_create_product_proto_rawDescOnce.Do(func() {
		file_rpc_create_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_product_proto_rawDesc), len(file_rpc_create_product_proto_rawDesc)))
	})
	return file_rpc_create_product_proto_rawDescData
}

var file_rpc_create_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil), // 0: pb.CreateProductRequest
	(*ProductResponse)(nil),      // 1: pb.ProductResponse
	(*Product)(nil),              // 2: pb.Product
}
var file_rpc_create_product_proto_depIdxs = []int32{
	2, // 0: pb.ProductResponse.product:type_name -> pb.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_product_proto_init() }
func file_rpc_create_product_proto_init() {
	if File_rpc_create_product_proto != nil {
		return
	}
	file_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_product_proto_rawDesc), len(file_rpc_create_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_product_proto_goTypes,
		DependencyIndexes: file_rpc_create_product_proto_depIdxs,
		MessageInfos:      file_rpc_create_product_proto_msgTypes,
	}.Build()
	File_rpc_create_product_proto = out.File
	file_rpc_create_product_proto_goTypes = nil
	file_rpc_create_product_proto_depIdxs = nil
}
