// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: service_inventory.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_inventory_proto protoreflect.FileDescriptor

const file_service_inventory_proto_rawDesc = "" +
	"\n" +
	"\x17service_inventory.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0frpc_stock.proto\x1a\x11rpc_product.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xef\x06\n" +
	"\tInventory\x12\x83\x01\n" +
	"\n" +
	"CheckStock\x12\x13.pb.GetStockRequest\x1a\x11.pb.StockResponse\"M\x92A4\x12\vCheck stock\x1a%Use this API to check a product stock\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/stocks\x12\x98\x01\n" +
	"\fReserveStock\x12\x13.pb.GetStockRequest\x1a\x11.pb.StockResponse\"`\x92A8\x12\rReserve stock\x1a'Use this API to reserve a product stock\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/stocks/{code}/reserve\x12\x98\x01\n" +
	"\fReleaseStock\x12\x13.pb.GetStockRequest\x1a\x11.pb.StockResponse\"`\x92A8\x12\rRelease stock\x1a'Use this API to release a product stock\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/stocks/{code}/release\x12\x8d\x01\n" +
	"\rCreateProduct\x12\x18.pb.CreateProductRequest\x1a\x13.pb.ProductResponse\"M\x92A2\x12\x0eCreate product\x1a Use this API to create a product\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/products\x12\x83\x01\n" +
	"\n" +
	"GetProduct\x12\x15.pb.GetProductRequest\x1a\x13.pb.ProductResponse\"I\x92A,\x12\vGet product\x1a\x1dUse this API to get a product\x82\xd3\xe4\x93\x02\x14\x12\x12/api/products/{id}\x12\x8f\x01\n" +
	"\rDeleteProduct\x12\x15.pb.GetProductRequest\x1a\x16.google.protobuf.Empty\"O\x92A2\x12\x0eDelete product\x1a Use this API to delete a product\x82\xd3\xe4\x93\x02\x14*\x12/api/products/{id}B>\x92A\x16\x12\x14\n" +
	"\rInventory API2\x031.0Z#github.com/ymanshur/synasishouse/pbb\x06proto3"

var file_service_inventory_proto_goTypes = []any{
	(*GetStockRequest)(nil),      // 0: pb.GetStockRequest
	(*CreateProductRequest)(nil), // 1: pb.CreateProductRequest
	(*GetProductRequest)(nil),    // 2: pb.GetProductRequest
	(*StockResponse)(nil),        // 3: pb.StockResponse
	(*ProductResponse)(nil),      // 4: pb.ProductResponse
	(*empty.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_service_inventory_proto_depIdxs = []int32{
	0, // 0: pb.Inventory.CheckStock:input_type -> pb.GetStockRequest
	0, // 1: pb.Inventory.ReserveStock:input_type -> pb.GetStockRequest
	0, // 2: pb.Inventory.ReleaseStock:input_type -> pb.GetStockRequest
	1, // 3: pb.Inventory.CreateProduct:input_type -> pb.CreateProductRequest
	2, // 4: pb.Inventory.GetProduct:input_type -> pb.GetProductRequest
	2, // 5: pb.Inventory.DeleteProduct:input_type -> pb.GetProductRequest
	3, // 6: pb.Inventory.CheckStock:output_type -> pb.StockResponse
	3, // 7: pb.Inventory.ReserveStock:output_type -> pb.StockResponse
	3, // 8: pb.Inventory.ReleaseStock:output_type -> pb.StockResponse
	4, // 9: pb.Inventory.CreateProduct:output_type -> pb.ProductResponse
	4, // 10: pb.Inventory.GetProduct:output_type -> pb.ProductResponse
	5, // 11: pb.Inventory.DeleteProduct:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_inventory_proto_init() }
func file_service_inventory_proto_init() {
	if File_service_inventory_proto != nil {
		return
	}
	file_rpc_stock_proto_init()
	file_rpc_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_inventory_proto_rawDesc), len(file_service_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_inventory_proto_goTypes,
		DependencyIndexes: file_service_inventory_proto_depIdxs,
	}.Build()
	File_service_inventory_proto = out.File
	file_service_inventory_proto_goTypes = nil
	file_service_inventory_proto_depIdxs = nil
}
