Table inventory.products {
  id uuid [PK]
  code varchar [not null, unique]
  total int [not null, default: 0]
  hold int [not null, default: 0]
  updated_at timestamptz [not null, default: `now()`]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    code
  }
}

Table order.orders {
  id uuid [PK]
  order_no varchar [not null, unique]
  user_id uuid [not null]
  status stock_status [not null]
  expired_at timestamptz
  updated_at timestamptz [not null, default: `now()`]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    order_no
  }
}

Table order.order_details {
  id uuid [PK]
  order_id varchar [ref: > order.orders.id, not null]
  product_code varchar [not null]
  amount int [not null]
  updated_at timestamptz [not null, default: `now()`]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    order_id
  }
}

Enum stock_status {
  reserved
  setlled
  canceled
}
