name: CD

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Inventory Service
            context: .
            dockerfile: ./inventory-service/Dockerfile
            image: ${{ vars.DOCKER_USERNAME }}/synasishouse/inventory

    name: Build and publish ${{ matrix.name }} image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.9"

      - name: Run go mod vendor
        run: |
          if [ -f "${{ matrix.context }}/go.mod" ]; then
            echo "Running 'go mod vendor' in directory: ${{ matrix.context }}"
            cd ${{ matrix.context }}
            go mod vendor
          else
            echo "Skipping 'go mod vendor': go.mod not found in context directory."
          fi

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
