services:
  inventory-postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=synansishouse_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  inventory-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ymanshur/synasishouse:inventory-latest
    # expose only for the same network
    expose:
      - "9090"
    environment:
      - APP_GRPC_SERVER_ADDR=0.0.0.0:9090
      - APP_DB_NAME=synansishouse_inventory
      - APP_DB_HOST=inventory-postgres
      - APP_DB_PORT=5432
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_MIGRATION_URL=file://db/migration
    command: ["/app/main"]
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=0.0.0.0:9090"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
